from random import choice

def main_call(COMMANDS, MANIFEST=None):
    COMMANDS["fortune"] = fortune,

def fortune():
    fortunes = [
        "Stay hungry, stay foolish. — Steve Jobs",
        "Knowledge is power. — Francis Bacon",
        "Time is money. — Benjamin Franklin",
        "Simplicity is the ultimate sophistication. — Leonardo da Vinci",
        "What we think, we become. — Buddha",
        "The unexamined life is not worth living. — Socrates",
        "Fortune favors the bold. — Virgil",
        "To be is to do. — Socrates",
        "To do is to be. — Jean-Paul Sartre",
        "Do or do not. There is no try. — Yoda",
        "Life is really simple, but we insist on making it complicated. — Confucius",
        "The journey is the reward. — Steve Jobs",
        "Imagination is more important than knowledge. — Albert Einstein",
        "Wisdom begins in wonder. — Socrates",
        "Everything should be made as simple as possible. — Albert Einstein",
        "Well done is better than well said. — Benjamin Franklin",
        "Action is eloquence. — William Shakespeare",
        "Knowledge speaks, wisdom listens. — Jimi Hendrix",
        "The only source of knowledge is experience. — Albert Einstein",
        "Dream big and dare to fail. — Norman Vaughan",
        "Turn your wounds into wisdom. — Oprah Winfrey",
        "Whatever you are, be a good one. — Abraham Lincoln",
        "The secret of getting ahead is getting started. — Mark Twain",
        "Never, never, never give up. — Winston Churchill",
        "Quality is not an act, it is a habit. — Aristotle",
        "The purpose of our lives is to be happy. — Dalai Lama",
        "Life is what happens when you're busy making other plans. — John Lennon",
        "Knowing yourself is the beginning of all wisdom. — Aristotle",
        "If you judge people, you have no time to love them. — Mother Teresa",
        "The future depends on what you do today. — Mahatma Gandhi",
        "Happiness depends upon ourselves. — Aristotle",
        "Adventure is worthwhile. — Aesop",
        "The best revenge is massive success. — Frank Sinatra",
        "Doubt kills more dreams than failure ever will. — Suzy Kassem",
        "Try to be a rainbow in someone's cloud. — Maya Angelou",
        "Every moment is a fresh beginning. — T.S. Eliot",
        "Change the world by being yourself. — Amy Poehler",
        "Reality leaves a lot to the imagination. — John Lennon",
        "The only journey is the one within. — Rainer Maria Rilke",
        "Believe you can and you're halfway there. — Theodore Roosevelt",
        "The best way out is always through. — Robert Frost",
        "Life shrinks or expands in proportion to one's courage. — Anaïs Nin",
        "Nothing will work unless you do. — Maya Angelou",
        "The way to get started is to quit talking and begin doing. — Walt Disney",
        "Success is not final, failure is not fatal. — Winston Churchill",
        "Do what you can, with what you have, where you are. — Theodore Roosevelt",
        "If opportunity doesn't knock, build a door. — Milton Berle",
        "Everything you can imagine is real. — Pablo Picasso",
        "In the middle of difficulty lies opportunity. — Albert Einstein",
        "The only limit to our realization of tomorrow is our doubts of today. — Franklin D. Roosevelt"
    ]

    print(f"\n{choice(fortunes)}")